---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: debian-7.4

suites:
  - name: default
    run_list:
      - recipe[storm::default]
    attributes:
  - name: singlenode
    run_list:
      - recipe[storm::singlenode]
    attributes:
